"""Add connected_wallet to Wallet

Revision ID: 6df41f011590
Revises: d714063daa72
Create Date: 2026-05-05 01:02:14.131477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df41f011590'
down_revision: Union[str, Sequence[str], None] = 'd714063daa72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('connected_wallet', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'connected_wallet')
    # ### end Alembic commands ###
