"""Add card model

Revision ID: d714063daa72
Revises: fb411f7e86e7
Create Date: 2026-05-04 12:38:38.433221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd714063daa72'
down_revision: Union[str, Sequence[str], None] = 'fb411f7e86e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=10), nullable=False),
    sa.Column('cvv', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.drop_column('wallets', 'usdt_trc20_deposit_address')
    op.drop_column('wallets', 'btc_deposit_address')
    op.drop_column('wallets', 'usdt_erc20_deposit_address')
    op.drop_column('wallets', 'eth_deposit_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('eth_deposit_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('usdt_erc20_deposit_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('btc_deposit_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('usdt_trc20_deposit_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
