"""Add custom deposit addresses

Revision ID: fb411f7e86e7
Revises: 6dd0f9066d14
Create Date: 2026-04-29 02:25:58.308821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb411f7e86e7'
down_revision: Union[str, Sequence[str], None] = '6dd0f9066d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('btc_deposit_address', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('eth_deposit_address', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('usdt_trc20_deposit_address', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('usdt_erc20_deposit_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'usdt_erc20_deposit_address')
    op.drop_column('wallets', 'usdt_trc20_deposit_address')
    op.drop_column('wallets', 'eth_deposit_address')
    op.drop_column('wallets', 'btc_deposit_address')
    # ### end Alembic commands ###
